### ISSUE TITLE
Adding a link to the public data science core page 

### ISSUE THREAD

**Issue by BoPeng** [ictr/data-science-core-website#2]
We can add a link at the bottom of https://www.bcm.edu/research/research-offices/institute-for-clinical-and-translational-research/service-cores/data-science that points to the website. To do that, we need to

1. make the repository publicly available.
2. Mark projects that are BCM Intranet Only so that public users will not be surprised. (@omid-jf )
3. Send an IT request to add the link.

@zhudakai  What is the process to modify the content of the public page?

**Comment by omid-jf** [comment]
> We can add a link at the bottom of https://www.bcm.edu/research/research-offices/institute-for-clinical-and-translational-research/service-cores/data-science that points to the website. To do that, we need to
> 
> 1. make the repository publicly available.
> 2. Mark projects that are BCM Intranet Only so that public users will not be surprised. (@omid-jf )
> 3. Send an IT request to add the link.
> 
> @zhudakai What is the process to modify the content of the public page?

1. Made the repo public.
2. Added BCM Intranet Only text.

**Comment by BoPeng** [comment]
Done. Added a link as "Projects and deployed applications". Also sent a request to add Omid and Thom as members.
